### ISSUE TITLE
Turn off for Some?

### ISSUE THREAD

**Issue by bradennapier** [amplify-education/serverless-vpc-discovery#15]
Is there no way to indicate specific functions that should not be placed within the VPC?  It seems to be a catch-all so all the lambdas need to be in VPC for the project.

Would be nice if we could specify a parameter within the function to turn off vpc inclusion for that function.

**Comment by jconstance-amplify** [comment]
Seems like a reasonable feature request to me. I think two paths for this would be to do as you've described and have a boolean that turns off the VPC settings provided by the plugin for a given function, or perhaps supporting configuring this plugin at the function level.

Is anyone interested in implementing either of those solutions?

**Comment by roni-frantchi** [comment]
@bradennapier @jconstance-amplify I have opened #19 that should resolve this issue.

**Comment by wduminy** [comment]
@bradennapier @roni-frantchi 
maybe you have read this [blog](https://dev.to/hoangleitvn/how-to-toggle-vpc-configuration-per-stage-4abp).  I like the approach described there.  However it does not work anymore.  Should we not just be able to omit the `vpc` section for a stage?
