### ISSUE TITLE
VPC not found

### ISSUE THREAD

**Issue by cscetbon** [amplify-education/serverless-vpc-discovery#16]
It seems the plugin does not use `provider.region` if it's set. It looks similar to https://github.com/amplify-education/serverless-vpc-discovery/issues/4 where you try to get the profile from the serverless configuration except that here it's the region that I set.

**Comment by rddimon** [comment]
Hey @cscetbon 
Could you please try the latest version of the plugin?

**Comment by rddimon** [comment]
It has been fixed in version `2.0.0`

**Comment by cscetbon** [comment]
Sorry that was so long ago that I can’t easily test it

**Comment by rddimon** [comment]
Hi @cscetbon, np

Just try our new release and let us know in case any issue
