### ISSUE TITLE
Possible Contributor?

### ISSUE THREAD

**Issue by corydorning53** [amplify-education/serverless-vpc-discovery#32]
Is it possible to add some contributors that can merge the PRs?

**Comment by aoskotsky-amplify** [comment]
Hey @corydorning53, sorry for the long delay in reviewing the PRs. We are going to start working on this again and get the outstanding PRs merged. 

We just did a new release that refactored a bunch of the code and rewrote it in Typescript. There will be tons of merge conflicts now but we'll take care of those
