### ISSUE TITLE
Doesn't work behind corporate proxy

### ISSUE THREAD

**Issue by corydorning53** [amplify-education/serverless-vpc-discovery#33]
The fix is pretty straightforward and I'm happy to create a PR assuming it will be merged. Instead of using the `aws-sdk` to create the `ec2` instance, it should be done via the serverless aws-sdk.

In `updateVpcConfig()` instead of having this:
```
const awsCreds = this.serverless.providers.aws.getCredentials();
awsCreds.region = this.serverless.providers.aws.getRegion();

AWS.config.update(awsCreds);
AWS.config.update({
  maxRetries: 20,
});

this.ec2 = new AWS.EC2();
```

it should be this:
```
this.ec2 = new this.serverless.providers.aws.sdk.EC2({
  maxRetries: 20,
  region: this.serverless.providers.aws.getRegion()
});
```

**Comment by corydorning53** [comment]
This would also allow the removal of the aws-sdk dependency.

**Comment by rddimon** [comment]
@corydorning53 Could you please try the latest version?

**Comment by rddimon** [comment]
It has been fixed in version `2.0.0`

**Comment by corydorning** [comment]
Happy to give this a go, but still need pr #19  and #30  for my use case

**Comment by rddimon** [comment]
@corydorning We are working on new features in this [PR](https://github.com/amplify-education/serverless-vpc-discovery/pull/34)
Going to release it by the end of this week
