### ISSUE TITLE
Version 2.2.0 does not work with serverless version 2.1.4

### ISSUE THREAD

**Issue by pda75** [amplify-education/serverless-vpc-discovery#37]
$ serverless package --stage dev --region us-east-1 --vpc CBORD-APP-VPC
Serverless: Running "serverless" installed locally (in service node_modules)

  Serverless Error ---------------------------------------

  Serverless plugin "serverless-vpc-discovery" not found. Make sure it's installed and listed in the "plugins" section of your serverless con
fig file.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information ---------------------------
     Operating System:          win32
     Node Version:              12.18.3
     Framework Version:         2.14.0
     Plugin Version:            4.1.2
     SDK Version:               2.3.2
     Components Version:        3.4.3

If I roll back the plugin to version 2.1.0 everything is fine.

npm install serverless-vpc-discovery@2.1.0

$ serverless package --stage dev --region us-east-1 --vpc CBORD-APP-VPC
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless VPC Discovery: Info: Updating VPC config...
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Excluding development dependencies...
Serverless: Merged stage variables into ApiGateway Deployment

**Comment by rddimon** [comment]
@pda75 Hi
Thank you for the reported issue

**Comment by pda75** [comment]
No problem.  Thanks for fixing so quickly.  Our serverless builds all started blowing up this AM and the quick fix will mean we don’t have to update a lot of build scripts.

Paul
