### ISSUE TITLE
Serverless schema validation issues

### ISSUE THREAD

**Issue by ROSeaboyer** [amplify-education/serverless-vpc-discovery#51]
Serverless introduced a change recently to enforce schema validation to catch configuration errors before attempting to make a deployment to CloudFormation. This doesn't cause any issues for anything within the custom section of serverless.yml, but it does cause issues for the vpcDiscovery configuration section being added to individual lambda functions.

Is there a plan in place to add that configuration into this plugin, or is that something that a PR would be helpful with? I just want to make sure I wouldn't be stepping on toes before trying my hand at it

**Comment by rddimon** [comment]
Hey @ROSeaboyer,

Thank you for your request!

We are going to make changes soon for publishing the plugin via GitHub workflow.
So feel free to create a PR we will review and merge it

**Comment by rddimon** [comment]
Hi @ROSeaboyer 
We have merged your changes.

Thank you for your work!

Closing this issue
