### ISSUE TITLE
Improve readme around tags

### ISSUE THREAD

**Issue by wduminy** [amplify-education/serverless-vpc-discovery#71]
In the readme I see
> The vpc discovery plugin takes the given vpc name, subnet tag key/value, and security group tag key/value or names in the serverless file to setup the vpc configuration for the lambda.

But is it not clear what the values of the tags should be. For example, what are the valid values for `securityGroups.tagKey`
```json
 securityGroups:
      - tagKey: <tag_name>
 ```

An easy fix could be to update the readme file and use real values instead of  place holders (`<tag_name>`) so that one can see how the config translates to the _generated config_.

**Comment by rddimon** [comment]
Hi @wduminy 

We don't know your real values that is why used some examples.

[Here](https://github.com/amplify-education/serverless-vpc-discovery/blob/main/test/integration-tests/basic/basic-example/serverless.yml) you can find a better example of the config.

Please try our latest version and let us know in case of any issues.
