### ISSUE TITLE
Install not working correctly

### ISSUE THREAD

**Issue by Ryan-og** [amplify-education/serverless-vpc-discovery#74]
When I install via npm it only partially adds the files and the plugin doesn't work (--env not recognised). however if I just clone the whole repo locally all of the test commands run as expected. also npm test is an invalid command, it should be npm run test I think. Any advice would be appreciated.

**Comment by rddimon** [comment]
Hi @Ryan-og

The `--env` option got deprecated please specify your VPC config via serverless config.
Please try our latest version and let us know in case of any issues.
