### ISSUE TITLE
VPC lookup happens for every lambda in serial and takes a long time for large projects

### ISSUE THREAD

**Issue by tylerwalts** [amplify-education/serverless-vpc-discovery#76]
On an existing large (~75 endpoints) serverless framework project we moved it to a VPC which is managed outside of serverless.

This plugin works to get the job done, but it is much slower than before since the lookup now seems to happen in series for every function in the project.

Is there a way to get it to only lookup the VPC once, and then re-use the value for all the rest?

**Comment by jacobmaurer** [comment]
FWIW - we're seeing the same bottleneck with our project with a good number of endpoints - it takes quite a while to discover each one sequentially. Perhaps it could be updated with a configurable option to discover them in parallel instead?

**Comment by jacobmaurer** [comment]
After poking around a bit, I think all it would take is a `Promise.all()` wrapper around https://github.com/amplify-education/serverless-vpc-discovery/blob/main/src/index.ts#L116, but for more controlled and configured concurrency, obviously a bit more involved (could use `bluebird` `map` with `concurrency` or equivalent)
