### ISSUE TITLE
AWS SDK V2 Required Dependency

### ISSUE THREAD

**Issue by MarcDOLF** [amplify-education/serverless-vpc-discovery#77]
Hi, 
we are currently evaluating the use of this plugin for our project.

We noticed that this plugin requires the AWS SDK v2 in the deployment package.
Unfortunately the version 2 of the SDK is outdated. This old version of the SDK leads to a quite large bundle size.

Are there plans to update this tool to the newer AWS SDK Version?

**Comment by rddimon** [comment]
Hi @MarcDOLF 

Thank you for the question!

We will work on it for sure in the future but there is a V2 [dependency](https://github.com/serverless/serverless/blob/main/package.json#L32) on the serverless side.
Which are not allowing us to fully drop V2 right now.
